version: '3'
services:
  todo-service:
    build: ./todo-service
    env_file:
      - ./todo-service/.env
    ports: 
      - 3001:3001
    volumes:
      - ./todo-service:/usr/src/app
  web-service:
    # image: nginx:stable
    build: ./web-service
    env_file:
      - ./web-service/.env
    ports:
      - 3000:3000
    volumes:
      - ./web-service:/usr/src/app